version: "3.9"
services:
  pluto_db:
    image: postgres:latest
    restart: always
    ports:
      - 5434:5434
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: prototype
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: -p 5434
volumes:
  pgdata:
